#use_frameworks!

platform :ios, '9.0'

target 'DBInvalidApplePay_Example' do
  pod 'DBInvalidApplePay', :path => '../'
  
  pod 'AJKit', '0.1.0'
  
  target 'DBInvalidApplePay_Tests' do
    inherit! :search_paths

    
  end
end
