use_frameworks!

platform :ios, '8.0'

target 'DBInvalidApplePay_Example' do
  pod 'DBInvalidApplePay', :path => '../'

  target 'DBInvalidApplePay_Tests' do
    inherit! :search_paths

    
  end
end
